#!/bin/bash

for i in {1..30}
do
    if [[ $i -lt 10 ]]
    then
        archive_name=""$1"USDT-trades-2021-06-0"$i".zip"
    else
        archive_name=""$1"USDT-trades-2021-06-"$i".zip"
    fi
    echo "Downloading $archive_name"
    wget "https://data.binance.vision/data/spot/daily/trades/"$1"USDT/"$archive_name""
    unzip $archive_name -d .
    rm $archive_name
done
mkdir -p "./data/trades"
cat "$1USDT"*.csv > "data/trades/$1_trades.csv"
rm "$1USDT"*.csv